# Generated by Django 2.1.2 on 2019-03-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Course', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Dept')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('date', 'time')},
        ),
        migrations.AddField(
            model_name='exam_student',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Student'),
        ),
        migrations.AddField(
            model_name='exam_faculty',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Faculty'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DateField', to='exam_app.Slot'),
        ),
        migrations.AddField(
            model_name='exam',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Room'),
        ),
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharField', to='exam_app.Slot'),
        ),
        migrations.AddField(
            model_name='course',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Dept'),
        ),
        migrations.AlterUniqueTogether(
            name='exam_student',
            unique_together={('cid', 'sid')},
        ),
        migrations.AlterUniqueTogether(
            name='exam_faculty',
            unique_together={('cid', 'fid')},
        ),
    ]
